### ISSUE TITLE
django debug and secret key

### ISSUE THREAD

**Issue by JamesRocker-Simply** [TheRockerfly/my_cv_site#1]
Django secret key has been exposed to the public and debug mode has still been left on.
To resolve, generate a new key, update the github secret and turn off the debug mode. 

The secret will also need to be available for Heroku for deployment

**Comment by PhysicistSouravDas** [comment]
Django `SECRET_KEY` can be generated from [djecrety.ir](https://djecrety.ir/). Then save the `SECRET_KEY` in the environment variable of your Heroku dyno. 

Go to the settings of your Heroku app (https://dashboard.heroku.com/apps/<app_name>/settings), then click "Reveal Config Vars". Now, add `SECRET_KEY` in the  **KEY** and the "generated secret_key" in the **VALUE**. Then click **Add**.

I am updating the code (which will fetch `SECRET_KEY` from Heroku) and will create the Pull Request.

**Comment by PhysicistSouravDas** [comment]
With the Pull Request #2, this issue is resolved. And the Pull Request was accepted and changes were merged to `master` branch. The following changes have been done.
- [x] `SECRET_KEY` hidden in system environment variables.
- [x] `DEBUG` set to `True`

So, this issue can now be _closed_.

**Comment by JamesRocker-Simply** [comment]
Thanks again @PhysicistSouravDas saved me some of my free time trying to resolve this :D
